### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by MarcoIeni** [rust-lang/sync-team#87]
There are many outdated dependencies. Please update them 👍

You don't need to do all changes in one PR. Small PRs are appreciated, especially if huge code changes are required. 👍

**Comment by Makuo12** [comment]
Hey @MarcoIeni , I would like to contribute to updating the outdated dependencies. Please can you give further details to how i can go about it.

**Comment by MarcoIeni** [comment]
Hi! You can try to update some dependencies and check if the code still complies. Then raise a PR 👍
