### ISSUE TITLE
switch from `derive_builder` to `bon`

### ISSUE THREAD

**Issue by MarcoIeni** [rust-lang/sync-team#96]
[bon](https://github.com/elastio/bon) allows to create builders without the need of unwrapping.
Moving to this library would allow us to remove `unwrap`s and `expect`s all over the codebase. Wdyt?

**Comment by Kobzol** [comment]
Could you clarify "remove unwraps and expects all over the codebase"? I think that we currently only use `Builder` for the `TeamData` struct in tests, and I don't see (m)any unwraps related to that.

**Comment by MarcoIeni** [comment]
Yeah, sorry, I thought panics were more wide spread across the codebase 👍
